name: velock_app
description: "FH Hagenberg Semester Project"
publish_to: 'none' # This ensures the package is not published publicly
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_database: ^11.3.0
  geocoding: ^3.0.0
  flutter_local_notifications: ^18.0.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  flutter_map_location_marker: ^9.1.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/velock_intro.json
    - assets/images/velock.png
    - assets/lottie/authentication.json
    - assets/images/open.png
    - assets/images/close.png
    - assets/lottie/profile.json
    - assets/lottie/loader.json
    - assets/lottie/no_history.json
    - .env

flutter_native_splash:
  color: "#ffffff"                          # Background color of the splash screen
  image: "assets/images/velock.png"         # Logo for the native splash screen

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/velock_app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/velock_app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/velock_app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/velock_app_icon.png"
